bglb_blog/urls.py
import notifications.urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bglb_blog import settings
from blog.views import blog_list



urlpatterns = [
    path('admin/admin', admin.site.urls),
  
    path('', blog_list, name='home'),
    path('accounts/', include(('users.urls', 'users'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('oauth/', include(('oauth.urls', 'oauth'), namespace='oauth')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('comment/', include('comments.urls', namespace='comment')),
    path('message/', include('message.urls', namespace='message')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path

from blog import views

urlpatterns = [
    # path函数将url映射到视图
    re_path('blog-list/?key=value/', views.blog_list, name='blog_list'),
    re_path('blog-list/', views.blog_list, name='blog_list'),
    re_path('blog-edit/', views.blog_edit, name='blog_edit'),
    re_path('^blog-edit/?id=value$', views.blog_edit, name='blog_edit'),
    re_path('^(?P<username>\w+)$', views.blog_author, name='blog-author'),
    re_path('^blog-detail/(?P<id>\d+)$', views.blog_detail, name='blog-detail'),
    re_path('blog-publish/', views.blog_publish, name='blog_publish'),
    re_path('blog-delete/', views.blog_delete, name='blog_delete'),
    re_path('blog-upimage/', views.blog_image, name='blog_upimage'),
    re_path('blog-click/', views.blog_click, name='blog_click'),

]

users/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm
from django.urls import re_path
from . import views

app_name = 'users'
urlpatterns = [
    # re_path和path的作用都是一样的。只不过re_path是在写url的时候可以用正则表达式，功能更加强大。
    re_path(r'reg/', views.user_reg, name='reg'),
    re_path(r'login/', views.user_login, name='login'),
    re_path(r'profile/', views.profile, name='profile'),
    re_path(r'logout/', views.user_logout, name='logout'),
    re_path(r'update_password/', views.update_password, name='update_password'),
    re_path(r'reset_password/', views.reset_password, name='reset_password'),
    re_path(r'update_email/', views.update_email, name='update_email'),
    re_path(r'email_result/', views.email_result, name='email_result'),
    re_path(r'activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/', views.activate, name='activate_result'),
]

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %} 登录|蓝白社区 {% endblock title %}
{% block content %}
    <link rel="stylesheet" href="{% static  "css/signin.css" %}">
    <div class="container text-center">
    <div class="row">
        <div class="col-md-12">
            <form class="form-signin">
                     {% csrf_token %}
                <img class="mb-5" src="{% static "img/logo_font.png" %}" alt="LOGO" width="130px">
                <div class="form-group">
                    <label for="inputUsername" class="sr-only">用户名</label>
                    <input autocomplete type="text" id="username" class="form-control" placeholder="用户ID或邮箱" required
                           autofocus>
                </div>
                <div class="form-group">
                    <label for="inputPassword" class="sr-only">密码</label>
                    <input autocomplete type="password" id="password" class="form-control" placeholder="用户密码" required>
                </div>
            </form>
            <div class="">
                <button class="btn btn-lg btn-primary login" id="login" value="Login">登录</button>
                <a class="btn btn-lg btn-primary reg" href="{% url "accounts:reg" %}">注册</a><br>
                <a href="javascript:;" data-toggle="modal" data-backdrop="false" data-target="#forget_password_modal">忘记密码</a>
            </div>
            <hr>
               
            <div>
                {% load oauth_tags %}
                {% load_oauth_applications request %}
            </div>
        </div>
    </div>
</div>

    <div class="modal fade" tabindex="-1" id="forget_password_modal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- 模态框头部 -->
                <div class="modal-header">
                    <h4 class="modal-title">重置密码</h4>
                    <button type='button'  class="close" data-dismiss="modal" aria-label="Close" ><span aria-hidden="true" >&times;</span></button>
                </div>


                <!-- 模态框主体 -->
                <div class="modal-body">

                    <form>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">注册邮箱</label>
                            <input type="email" autocomplete class="form-control" name="email" id="email"
                                   placeholder="注册邮箱">
                        </div>
                        <div class="form-group ">
                            <label for="new_pwd">新密码：</label>
                            <input type="password" class="form-control" id="new_pwd" name="new_password"
                                   autocomplete>
                        </div>
                        <div class="form-group">
                            <label for="re_new_pwd">确认密码：</label>
                            <input type="password" class="form-control" id="re_new_pwd" name="re_password"
                                   autocomplete>
                        </div>
                        <div class="form-group">
                            <label for="re_new_pwd">验证码</label>
                            <input type="text" class="form-control" maxlength="6" id="yzm" name="yzm">
                        </div>

                    </form>

                    <!-- 模态框底部 -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary reset_password">确认修改</button>
                        <a href="javascript:;" class="send_reset_password_yzm">获取验证码</a>
                    </div>
                    {% csrf_token %}
                </div>
            </div>
        </div>
    </div>

 <script src="{% static "js/login.js" %}"></script>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}
{% load user_tags %}
{% block title %}{{ request.user.username }}的个人信息|蓝白社区{% endblock %}
{% block content %}

    <style>
        .avatar {
            width: 100px;
            height: 100px;
        }

        * {
            margin: 0 0;
        }

        .list-group a {
            background-color: #f7f7f7;
        }
    </style>
    <div class="container">

        <div class="row">
            <div class="list-group col-md-2 text-center">
                <a id="tab1" href="javascript:;" class="tab list-group-item active">个人资料</a>
                <a id="tab2" href="javascript:;" class="tab list-group-item">修改邮箱</a>
                <a id="tab3" href="javascript:;" class="tab list-group-item">修改密码</a>
                <a id="tab4" href="javascript:;" class="tab list-group-item">个人隐私</a>
            </div>
            <div class="col-md-6">
                <div id="tab-item1" class="tab-item">
                    <div class="row">
                        <div class="col-md-12 offset-1">
                            <h3>个人资料</h3>
                            <hr>
                            <div class="flex-fill">
                                <img src="{{ profile.avatar.url }}" class="rounded-circle avatar"/>
                                <button class="btn btn-sm btn-link" data-toggle="modal" data-target="#myModal">
                                    修改头像
                                </button>
                                <form action="." method="post" id="avaterForm" class="form"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="file" id="new_avatar" name="avatar" style="display: none">
                                </form>
                                <br>
                            </div>
                            <p>ID：{{ request.user.username }}</p>
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 offset-1">
                            <form method="post" action="." class="col-md-12">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="nickname">昵称：</label>
                                    <input type="text" class="form-control" id="nickname" name="nickname"
                                           value="{{ profile.nickname }}">
                                </div>
                                <div class="form-group">
                                    <label for="gender">性别：</label><br>
                                    {% if profile.gender == "男" %}
                                        <label class="radio-inline "><input type="radio" value="男" checked
                                                                            name="gender">男</label>
                                        <label class="radio-inline offset-3"><input type="radio" value="女"
                                                                                    name="gender">女</label>
                                    {% else %}
                                        <label class="radio-inline"><input type="radio" value="男"
                                                                           name="gender">男</label>
                                        <label class="radio-inline offset-3"><input type="radio" value="女" checked
                                                                                    name="gender">女</label>
                                    {% endif %}

                                </div>
                                <div class="form-group">
                                    <label for="age">年龄：</label>
                                    <input type="text" class="form-control" id="age" name="age"
                                           value="{{ profile.age }}">
                                </div>
                                <div class="form-group  ">
                                    <label for="sign">个性签名</label>
                                    <textarea class="form-control" id="sign" name="sign"
                                              rows="3" placeholder="简单的介绍下自己吧~">{{ profile.sign }}</textarea>
                                </div>
                                <button type="submit" class="btn btn-primary " onclick="bs4pop.notice('正在提交...')">提交
                                </button>
                            </form>
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="myModalLabel">上传头像</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                                &times;
                                            </button>
                                        </div>
                                        <div class="modal-body text-center">
                                            <span>
                                                <img src="" alt='新头像'
                                                     class="rounded-circle avatar new_avatar_pre">
                                            </span>

                                        </div>
                                        <div class="modal-footer">
                                            <!--点击选择文件-->
                                            <button type="button" class="btn btn-default update_avatar">本地上传</button>
                                            <!--点击提交表单-->
                                            <button type="button" class="btn btn-primary update_img">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="tab-item2" class="tab-item">
                    <div class="col-md-8 flex">
                        <h3>修改邮箱</h3>
                        <hr>
                    </div>
                    <div class="col-md-8 text-input">
                        <span><small>验证码会发送到您的注册邮箱{{ request.user.email|slice:3 }}***中<br>注意：更改邮箱之后需要重新激活邮箱，验证失败会导致您账号登录不成功</small></span>
                        <form action="" class="col-md-6" id="update_email">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="new_email">新邮箱：</label>
                                <input type="email" class="form-control" id="new_email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label for="yzm">验证码：</label>
                                <input type="text" maxlength="6" class="form-control" id="yzm" name="yzm"
                                       value="" required>
                                <a class="send_update_email_yzm" href="javascript:;">获取验证码</a>
                            </div>

                        </form>
                        <button class="btn btn-success update_email">提交</button>
                    </div>
                </div>
                <div id="tab-item3" class="tab-item">
                    <div class="col-md-8 flex">
                        <h3>修改密码</h3>
                        <hr>
                    </div>
                    <div class="col-md-8">
                        <form action="/accounts/update_password/" method="post" class="col-md-6 update_password_form">
                            {% csrf_token %}
                            <div class="form-group ">
                                <label for="new_pwd">新密码：</label>
                                <input type="password" class="form-control" id="new_pwd" name="new_password" value=""
                                       required>
                            </div>
                            <div class="form-group">
                                <label for="re_new_pwd">确认密码：</label>
                                <input type="password" class="form-control" id="re_new_pwd" name="re_password" value=""
                                       required>
                            </div>
                        </form>
                        <button class="btn btn-success update_password">提交</button>


                    </div>
                </div>
                <div id="tab-item4" class="tab-item">
                    <div class="col-md-8 flex">
                        <h3>个人隐私</h3>
                        <hr>
                    </div>
                    <div class="col-md-8">
                        <form method="post" action=".">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="is_display">是否在个人主页显示隐私信息：</label><br>

                                <label class="radio-inline "><input type="radio" value="True"
                                                                    {% if profile.is_display %}checked{% endif %}
                                                                    name="is_display">显示</label>
                                <label class="radio-inline offset-3"><input type="radio" value="False"
                                                                            {% if not profile.is_display %}checked{% endif %}
                                                                            name="is_display">不显示</label>


                            </div>
                            <div class="form-group ">
                                <label for="telephone">身份or职业</label>
                                <input type="text" class="form-control" id="site" name="occupation"
                                       value="{{ profile.occupation }}">
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="qq">qq：</label>
                                <input type="text" class="form-control" id="qq" name="qq"
                                       value="{{ profile.qq }}">
                            </div>

                            <div class="form-group">
                                <label for="telephone">电话</label>
                                <input type="text" class="form-control" id="telephone" name="telephone"
                                       value="{{ profile.telephone }}">
                            </div>
                            <div class="form-group">
                                <label for="github">GitHub</label>
                                <input type="text" placeholder="填写链接哦~" class="form-control" id="github" name="github"
                                       value="{{ profile.github }}">
                            </div>
                            <div class="form-group">
                                <label for="site">个人站点</label>
                                <input type="text" placeholder="填写链接哦~" class="form-control" id="site" name="site"
                                       value="{{ profile.site }}">
                            </div>
                            <button type="submit" class="btn btn-primary " onclick="bs4pop.notice('正在提交...')">提交
                            </button>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <script src="{% static '/js/base.min.js' %}"></script>
    <script src="{% static '/js/profile.min.js' %}"></script>
{% endblock %}

templates/accounts/reg.html
{% extends 'base.html' %}
{% load static %}
{% block title %}注册{% endblock %}
{% block content %}

    <link rel="stylesheet" href="{% static "css/base.css" %}"/>
    <style>
        #picyzm {
            width: 100px;
            height: 30px;
            display: inline-grid;
            margin-top: 5px;
        }
    </style>

    <div id="reg" class="container w960 mt20">
        <div class="alertr alert-dismissible fade show">
        </div>
        <div id="processor">
            <ol class="processorBox oh">
                <li class="current">
                    <div class="step_inner fl">
                        <span class="icon_step">1</span>
                        <h4>填写基本信息</h4>
                    </div>
                </li>
                <li>
                    <div class="step_inner">
                        <span class="icon_step">2</span>
                        <h4>邮箱激活</h4>
                    </div>
                </li>
            </ol>

        </div>
        <div class="content">
            <div id="step1" class="step hide">
                <form id="step1_frm">
                    {% csrf_token %}
                    <div class="frm_control_group">
                        <label class="frm_label">用户名</label>
                        <div class="frm_controls">
                            <input type="text" autocomplete class="frm_input username" placeholder="数字和字母组合6~16位之间"
                                   maxlength="16"/>
                            <p class="frm_tips"></p>
                        </div>
                    </div>
                    <div class="frm_control_group">
                        <label class="frm_label">邮箱</label>
                        <div class="frm_controls">
                            <input type="email" autocomplete class="frm_input email" maxlength="30"/>
                            <p class="frm_tips"></p>
                        </div>
                    </div>
                    <div class="frm_control_group">
                        <label class="frm_label">密码</label>
                        <div class="frm_controls">
                            <input type="password" name="password" autocomplete placeholder="密码最少六位" class="frm_input passwd"/>
                            <p class="frm_tips"></p>
                        </div>
                    </div>
                    <div class="frm_control_group">
                        <label class="frm_label">再次输入密码</label>
                        <div class="frm_controls">
                            <input type="password" autocomplete name="password2" class="frm_input passwd2"/>
                        </div>
                    </div>
                    <div class="frm_control_group">
                        <label class="frm_label">验证码</label>
                        <div class="frm_controls verifycode">
                            <input type="text" name="" class="frm_input verifyCode" maxlength="4"/>
                        </div>
                        <span id="picyzm" type="blend"></span>
                    </div>

                </form>
                <div class="toolBar">
                    <button id="nextBtn" class="btn btn-primary">下一步</button>
                </div>
            </div>
            <div id="step2" class="step hide">
                <div class="w330">
                    <strong class="f16">亲爱的<span class="zc_username"></span>感谢注册，激活邮件已发送至你的注册邮箱 : <br/><span
                            class="zc_email"></span></strong>
                    <p class="c7b">请进入邮箱查看邮件，点击链接即可激活账号</p>
                    <p class="c7b mt20">没有收到邮件？</p>
                    <p>1. 请检查邮箱地址是否正确，你可以返回 <a href="#" class="c46">重新注册</a></p>
                    <p>2. 检查你的邮件垃圾箱</p>
                    <p>3. 若仍未收到确认，请尝试
                        <a class="" id="re_email" href="javascript:;">重新获取邮件内容</a>
                    </p>
                </div>
            </div>

        </div>
    </div>
    <script src="{% static "js/vericode.js" %}"></script>
    <script src="{% static "js/reg.min.js" %}"></script>

{% endblock %}

templates/accounts/user_active_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮箱绑定结果</title>
</head>
<body>
<script>
    function countDown() {
        var time = document.getElementById("Time");
        if (time.innerHTML == 0) {
            //等于0时清除计时
            window.location.href = "{{ url }}";
            rel = "external nofollow";
        } else {
            time.innerHTML = time.innerHTML - 1;
        }
    }
    {% if flag %}
        window.setInterval("countDown()", 1000);
    {% endif %}
</script>
{% if flag == None %}
    <p>网络异常，请检查您的网络！！！</p>
{% endif %}
{% if flag %}
    <p>{{ msg }} <span id="Time">5</span>秒后跳转到主页面</p>
{% endif %}
{% if not flag %}
    <p>{{ msg }}</p>
{% endif %}

</body>
</html>