bglb_blog/urls.py
import notifications.urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bglb_blog import settings
from blog.views import blog_list



urlpatterns = [
    path('admin/admin', admin.site.urls),
  
    path('', blog_list, name='home'),
    path('accounts/', include(('users.urls', 'users'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('oauth/', include(('oauth.urls', 'oauth'), namespace='oauth')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('comment/', include('comments.urls', namespace='comment')),
    path('message/', include('message.urls', namespace='message')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path

from blog import views

urlpatterns = [
    # path函数将url映射到视图
    re_path('blog-list/?key=value/', views.blog_list, name='blog_list'),
    re_path('blog-list/', views.blog_list, name='blog_list'),
    re_path('blog-edit/', views.blog_edit, name='blog_edit'),
    re_path('^blog-edit/?id=value$', views.blog_edit, name='blog_edit'),
    re_path('^(?P<username>\w+)$', views.blog_author, name='blog-author'),
    re_path('^blog-detail/(?P<id>\d+)$', views.blog_detail, name='blog-detail'),
    re_path('blog-publish/', views.blog_publish, name='blog_publish'),
    re_path('blog-delete/', views.blog_delete, name='blog_delete'),
    re_path('blog-upimage/', views.blog_image, name='blog_upimage'),
    re_path('blog-click/', views.blog_click, name='blog_click'),

]

users/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm
from django.urls import re_path
from . import views

app_name = 'users'
urlpatterns = [
    # re_path和path的作用都是一样的。只不过re_path是在写url的时候可以用正则表达式，功能更加强大。
    re_path(r'reg/', views.user_reg, name='reg'),
    re_path(r'login/', views.user_login, name='login'),
    re_path(r'profile/', views.profile, name='profile'),
    re_path(r'logout/', views.user_logout, name='logout'),
    re_path(r'update_password/', views.update_password, name='update_password'),
    re_path(r'reset_password/', views.reset_password, name='reset_password'),
    re_path(r'update_email/', views.update_email, name='update_email'),
    re_path(r'email_result/', views.email_result, name='email_result'),
    re_path(r'activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/', views.activate, name='activate_result'),
]

blog/models.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-18 11:45
# @Author   : BGLB
# @Software : PyCharm
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from bglb_blog.settings import DOMAIN


class Category(models.Model):
    """
    文章分类
    """
    name = models.CharField(verbose_name='博文分类', max_length=20)

    class Meta:
        verbose_name = '博文分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    文章标签
    """
    name = models.CharField(verbose_name='博文标签', max_length=20)

    class Meta:
        verbose_name = '博文标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogPost(models.Model):
    """
    博文
    """
    title = models.CharField(verbose_name='标题', max_length=100)
    blog_type = models.CharField(verbose_name='文章类型', max_length=2, default='公开')
    content = models.TextField(verbose_name='正文', default='')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    modify_time = models.DateTimeField(verbose_name='修改时间')
    click_nums = models.IntegerField(verbose_name='浏览量', default=0)
    like = models.IntegerField(verbose_name='点赞数', default=0)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='文章类别', on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name='文章标签', blank=True)
    statu = models.CharField(verbose_name='文章状态', default="", max_length=5)

    # 草稿箱 回收站 公开 私密 正在编辑

    class Meta:
        verbose_name = '博文'
        verbose_name_plural = verbose_name
        ordering = ('-create_time',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:blog-detail', kwargs={
            'id': self.id,
        })

    def get_full_url(self):
        site = DOMAIN
        url = "{site}{path}".format(site=site,
                                    path=self.get_absolute_url())
        return url


class Links(models.Model):
    """友情链接"""

    name = models.CharField('链接名称', max_length=30, unique=True)
    link = models.URLField('链接地址')
    is_enable = models.BooleanField(
        '是否显示', default=True, blank=False, null=False)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Notice(models.Model):
    """公告内容"""
    title = models.CharField('公告标题', max_length=10)
    content = models.CharField('公告正文', max_length=30)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    is_enable = models.BooleanField(
        '是否显示', default=True, blank=False, null=False)

    class Meta:
        verbose_name = '公告'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class AD(models.Model):
    """广告内容"""
    title = models.CharField('广告标题', max_length=10)
    content = models.CharField('广告内容', max_length=30)
    img = models.CharField('图片地址', max_length=100)
    ad_link = models.CharField('广告链接', max_length=50)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    is_enable = models.BooleanField(
        '是否显示', default=True, blank=False, null=False)

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

blog/views.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:45
# @Author   : BGLB
# @Software : PyCharm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.utils.datetime_safe import datetime
from notifications.signals import notify
from blog.models import BlogPost, Tag
from django.db.models import Q
from django.core.paginator import Paginator
from blog.utils import update_img_file, blog_tag, blog_category
from comments.models import Comments
from django.utils.timezone import now

def blog_list(request):
    """博客列表页"""
    blog_list = BlogPost.objects.filter(statu='公开').all()
    blog_type = request.GET.get("blog_type", None)
    category = request.GET.get('category', None)
    search = request.GET.get('search', None)
    page = request.GET.get('page')
    if blog_type:
        blog_list = blog_list.filter(blog_type=blog_type).all()
    if category:
        blog_list = blog_list.filter(category=category).all()
    if search:
        blog_list = blog_list.filter(Q(title__icontains=search) | Q(content__icontains=search)|Q(category__name__icontains=search)|
            Q(tag__name=search)).distinct()
    else:
        search = ''
    paginator = Paginator(blog_list, 5)
    blog_list = paginator.get_page(page)
    return render(request, "blog/blog_list.html", locals())


@login_required()
def blog_edit(request):
    """编辑博客"""
    id = request.GET.get('id', None)
    if id is None:  # 新增请求 编辑上次保存的
        blog = BlogPost.objects.filter(author_id=request.user.id, statu='正在编辑').first()
        return render(request, "blog/blog_edit.html", locals())
    else:
        try:
            blog = BlogPost.objects.get(id=id, author_id=request.user.id)
            return render(request, 'blog/blog_edit.html', locals())
        except ObjectDoesNotExist as e:
            return render(request, '404.html', status=403)


def blog_author(request, username):
    user = get_object_or_404(User, username=username)
    blog_all = BlogPost.objects.filter(author_id=user.id).all()
    blog_tag = Tag.objects.filter(blogpost__author_id=user.id)
    blog_list = blog_all.filter(statu='公开')
    if request.user.username == username:
        blog_list_private = blog_all.filter(statu='私密')
        blog_list_del = blog_all.filter(statu="回收站")
        blog_list_drafts = blog_all.filter(statu='草稿箱')
    if blog_all:
        return render(request, 'blog/blog_author.html', locals())
    else:
        return render(request, 'blog/blog_author.html', {"msg": "期待您的创作"})


@login_required()
def blog_delete(request):
    blog_id = request.POST.get('id', None)
    if blog_id:
        blog = get_object_or_404(BlogPost, id=blog_id, author=request.user)

        if blog.statu == "回收站":
            blog.delete()
            msg = "文章已删除"
        else:
            blog.statu = "回收站"
            blog.modify_time = blog.modify_time
            msg = "文章已放入回收站"
            blog.save()
        flag = True

        return JsonResponse({"flag": flag, "msg": msg})

    else:
        return render(request, '404.html',status=404)


def blog_click(request):
    flag = False
    if request.method == "POST":

        blog_id = request.POST.get('id')
        blog = get_object_or_404(BlogPost, id=blog_id)
        blog.like = blog.like+1
        blog.modify_time = blog.modify_time
        blog.save()
        flag = True
        if request.user.is_authenticated:
            if request.user.id != blog.author.id:
                notify.send(request.user, recipient=blog.author, target=blog,
                            verb='给您的博文《{}》点赞啦'.format(blog.title))
        else:
            notify.send(User.objects.filter(is_superuser=True).first(), recipient=blog.author, target=blog,
                        verb='一位陌生人给您的博文《{}》点赞啦'.format(blog.title))

    return JsonResponse({"flag": flag})


def blog_detail(request, id):
    """文章预览和详情页"""
    blog = get_object_or_404(BlogPost, id=id)
    blog_comments = Comments.objects.filter(blog_id=id)
    if blog.statu != '公开' and blog.author != request.user:
        # 非公开的文章并且请求者不是作者 跳转404
        return render(request, '404.html', status=404)
    else:
        blog.click_nums += 1
        blog.modify_time = blog.modify_time
        blog.save()
        return render(request, 'blog/blog_detail.html', locals())


def blog_image(request):
    """上传图片"""
    if request.method == "POST":
        if 'editormd-image-file' in request.FILES:
            img = request.FILES.get('editormd-image-file')
            img_url = update_img_file(img)
            context = {"success": 0, "message": "服务器配置错误，请联系网站管理员进行修复！", 'url': -1}
            if img_url:
                context['success'] = 1
                context['url'] = img_url
            return JsonResponse(context)
    else:
        # get 请求跳转到404
        return render(request, '404.html',status=403)


@login_required()
def blog_publish(request):
    """
    保存博客
    :param request:
    :return:
    """
    if request.method == "POST":
        data = request.POST
        content = data.get("content")
        # 保存文章数据到数据库
        id = data.get('id', 0)
        if id != 0:
            blog = BlogPost.objects.filter(author_id=request.user.id, id=id)
        else:
            blog = BlogPost.objects.filter(author_id=request.user.id, statu='正在编辑')
        if blog.exists():
            blog = blog.first()
            blog.tag.clear()

        else:
            blog = BlogPost()
        blog.content = content
        blog.statu = data.get("statu")
        blog.author = User.objects.get(id=request.user.id)
        blog.category_id = data.get("category")
        blog.blog_type = data.get("type")
        blog.title = data.get('title')
        tag_list = []
        blog.modify_time = now()
        blog.save()
        if data.get("tag_add"):
            tag_add = blog_tag(data.get("tag_add"))
            # print(data.get("tag_add"))
            tag_list = tag_add
        if data.get('tag'):
            for tag in data.get('tag').split(','):
                tag_list.append(tag)
        # print(tag_list)
        if len(tag_list) > 0:
            tag_list = list(set(tag_list))
            if '' in tag_list:
                tag_list.remove('')
            blog.tag.add(*tag_list)

        context = {"flag": True, "message": "博文发布成功！", 'id': blog.id}
        return JsonResponse(context)
    else:
        context = {"categorys": blog_category(), 'tags': blog_tag()}
        return JsonResponse(context)


templates/blog/blog_category.html
{% if categorys %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blog_list' %} ">全部</a>
        </li>
        {% for cat in categorys %}
            <li>
                <a href="{{ url }}?category={{ cat.id }}" class="nav-link">{{ cat.name }}</a>
            </li>
        {% endfor %}
    </ul>

{% endif %}



templates/blog/blog_detail.html
{% extends 'base.html' %}{% load static %}
{% load user_tags %}
{% load blog_tools %}
{% block description %}
    <meta name="keywords" content="{{ blog.title }}|{{ blog.category }}|
            {% for foo in blog.tag.values %}{{ foo.name }}|{% endfor %}蓝白社区">

    <meta name="description" content="{{ blog.title|slice:":50" }}|{{ blog.content|slice:50 }}|蓝白社区">
{% endblock %}
{% block title %}{{ blog.title }}|{{ blog.author.id|nickname }}的博客|蓝白社区{% endblock %}
{% block artice %}
    <link rel="stylesheet" href="{% static 'edittormd/css/editormd.min.css' %}">
    <link rel="stylesheet" href="{% static 'edittormd/css/editormd.preview.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/comments.css' %}">
    <div id="toc">
        <div id="sideber" class='d-none d-md-block'>
            <h4>博文目录</h4>
            <div class="markdown-body editormd-preview-container d-none d-md-block" id="custom-toc-container">
                #custom-toc-container
            </div>
        </div>
    </div>
    <div class="container container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ blog.title }}</h2>
                <div class="article-info-box">
                    <div class="article-bar-top">
                        {% if blog.blog_type == '原创' %}
                            <img class="article-type-img" src="{% static 'img/original.png' %}"
                                 alt="原创">
                        {% else %}
                            <img class="article-type-img" src="{% static 'img/reprint.png' %}"
                                 alt="转载">
                        {% endif %}

                        <div class="bar-content">
                            <a class="follow-nickName" href="{% url 'blog:blog-author' blog.author %}" target="_blank"
                               rel="noopener">{{ blog.author }}</a>
                            <span class="time">{{ blog.modify_time }}</span>
                            <div class="up-time">
                                <span>最后发布:{{ blog.modify_time }}</span><span>首发:{{ blog.create_time }}</span>
                            </div>
                            <span class="icon-my icon-eye">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#i-kejian"></use>
                            </svg>
                                {{ blog.click_nums }}</span>

                            <span class="icon-my icon-zan">
                            <svg class="icon" aria-hidden="true">
                                <use xlink:href="#i-zan-red"></use>
                            </svg>
                                {{ blog.like }}</span>

                            </a>
                        </div>
                    </div>
                    <div class="blog-tags-box">

                        <small style="margin-top: 2px">博文分类：</small>
                        <div class="tags-box artic-tag-box">
                        <span class="label">{{ blog.category }}
                        </span>
                        </div>
                        <small style="margin-top: 2px">博文标签：</small>
                        {% for foo in blog.tag.values %}
                            <div class="tags-box artic-tag-box">
                                <span class="label">{{ foo.name }}</span>
                            </div>
                        {% endfor %}

                    </div>

                    <div class="slide-content-box">
                        <div class="all-tags-box">
                        </div>
                        <div class="article-copyright">
                            <div class="creativecommons">
                                <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"></a>
                            </div>
                            <div class="creativecommons">
                                版权声明：本文为博主[{{ blog.author.username }}]原创文章，遵循<a
                                    href="http://creativecommons.org/licenses/by/4.0/" target="_blank"
                                    rel="noopener">
                                CC 4.0 BY </a>版权协议，转载请附上原文出处链接和本声明。
                            </div>
                            <div class="article-source-link">
                                本文链接：<a
                                    href="{% url 'blog:blog-detail' blog.id %}">http://blog.bglb.work{% url 'blog:blog-detail' blog.id %}</a>
                            </div>
                        </div>
                    </div>
                    <div class="operating">
                        {% if blog.author == request.user %}
                            <a class="slide-toggle" href="/blog/blog-edit/?id={{ blog.id }}">编辑</a>
                        {% endif %}
                        <a class="href-article-edit slide-toggle">版权</a>
                    </div>
                </div>

                <div id="editormd" data-id="{{ blog.id }}">
                    <textarea style="display:none;">{{ blog.content|safe }}</textarea>
                </div>


            </div>

        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                {% csrf_token %}
                <button class="btn btn-light click">点赞<span
                        class="badge click_nums badge-primary">{{ blog.like }}</span>
                </button>
                <button class="btn btn-primary">打赏
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% include 'comments/comment_list.html' %}
                {% if request.user.is_authenticated %}
                    {% include 'comments/post_comment.html' %}
                {% else %}
                    请 <a href="/accounts/login/">登录</a>后评论
                {% endif %}
            </div>
        </div>


    </div>
    <script src="{% static 'edittormd/lib/marked.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/prettify.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/raphael.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/underscore.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'edittormd/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'edittormd/editormd.min.js' %}"></script>
    <script src="{% static 'js/blog_detail.js' %}"></script>

{% endblock %}

templates/blog/blog_edit.html
{% load static %}
{% load user_tags %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>博文创作|Markdown编辑器|蓝白社区</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
    {% block description %}
        <meta data-n-head="true" data-hid="description" name="description"
              content="蓝白社区,致力于分享IT技术,原创博客、技术论坛、资源共享等,提供原创、优质、完整内容的IT技术分享社区,社区创始人:半根蓝白，期待与您一起共建更加优质的社区环境">
        <meta name="keywords" content="Markdown编辑器,IT技术分享，博客，IT资源共享，蓝白社区">
    {% endblock %}
    <link href='{% static "img/favicon.ico" %}' rel="shortcut icon">
    <link rel="stylesheet" href="{% static 'edittormd/css/editormd.min.css' %}">
    <link rel="stylesheet" href="{% static 'edittormd/css/editormd.preview.min.css' %}">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/blog_edit_header.css" %}">
    <script src="{% static 'jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bs4.pop.js' %}"></script>
    <script src="{% static 'edittormd/editormd.min.js' %}"></script>
    <script src="{% static 'edittormd/plugins/image-handle-paste/image-handle-paste.js' %}"></script>


</head>
<body>


<div class="layout">
    <div class="layout__panel layout__panel--articletitle-bar" style="width: 100%; height: 56px; overflow: inherit;">
        <div class="article-bar flex flex--row flex--align-center">
            <div class="article-bar__link-box"><a title="返回主页" href="/blog/blog-list" class="btn btn-dark">
                返回主页</a></div>
            <div class="article-bar__input-box" id="title-blog"><input maxlength="100" placeholder="输入文章标题"
                                                                       value="{{ blog.title }}"
                                                                       class="article-bar__title article-bar__title--input text-input">
                <span class="article-bar__number"><span class="input-len">0</span>/100</span>
            </div>
            <div class="article-bar__user-box flex flex--row">

                <button class="btn btn-success btn-publish" data-toggle="modal">发布文章</button>
                <div class="user-box">
                    <div class="btn-userinfo">
                        <div class="avatar-box"><a><img
                                src="{{ request.user.id|avatar_url }}" alt="avatar" width="32"
                                height="32" class="img-user-avatar"> <!----></a></div>
                        <div class="user-option-box">
                            <a href="/blog/blog-list/">博文管理</a>
                            <a href="/blog/blog-list/{{ request.user.username }}">账号设置</a>
                            <a href="{% url 'accounts:logout' %}">退出登录</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="layout__panel flex flex--row"></div>

    <div class="modal fade" id="publics_modal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- 模态框头部 -->
                <div class="modal-header">
                    <h4 class="modal-title">文章详情</h4>
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- 模态框主体 -->
                <div class="modal-body">


                    <label for="blog_type">文章类型:</label>
                    <label class="radio-inline"><input type="radio" name="blog_type" value="转载">转载</label>
                    <label class="radio-inline"><input type="radio" name="blog_type" value="原创">原创</label>
                    <span class="notice" style="color: red">*</span><br/>

                    <lable class="inline_label"><label for="blog_category">文章分类<span class="notice"
                                                                                     style="color: red">*</span></label>
                        <select class="form-control" name="blog_categorys" id="blog_categorys" style="display:inline">
                            <option value="0">请选择</option>
                        </select></lable>


                    <label for="blog_tags">文章标签：（自定义可多选）</label>
                    <input type="text" class="form-control" name="blog_tag" placeholder="自定义标签1,自定义标签2,">
                    <select multiple class="form-control" id="blog_tags" name="blog_tags">

                    </select>
                    <label for="is_active">发布形式:<span class="notice" style="color: red">*</span><br/></label>
                    <label class="radio-inline"><input type="radio" name="is_active" value="公开">公开</label>
                    <label class="radio-inline"><input type="radio" name="is_active" value="私密">私密</label>
                    <label class="radio-inline"><input type="radio" name="is_active" value="草稿箱">存为草稿</label>


                    <!-- 模态框底部 -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">返回修改</button>
                        <button type="button" class="btn btn-primary" id="btn-update">确认发表</button>
                    </div>
                    {% csrf_token %}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="editormd" data-id='{{ blog.id }}'>
    <textarea style="display:none;">{{ blog.content }}</textarea>
</div>

{% csrf_token %}
    <script src="{% static 'js/blog_edit.js' %}"></script>

<script>

    var testEditor;

    $(function () {
        testEditor = editormd("editormd", {
            placeholder: '欢迎使用蓝白社区-Markdown编辑器\n提示：使用[TOC]可以自动生成目录，开始您的创作吧，相信您一定妙笔生花',
            width: "100%",
            height: '880',

            delay: 500,
            theme: "default",
            editorTheme: '3024-day',
            previewTheme: "default",
            emoji: true,
            taskList: true,
            tex: true,                   // 开启科学公式TeX语言支持，默认关闭
            flowChart: true,             // 开启流程图支持，默认关闭
            sequenceDiagram: true,       // 开启时序/序列图支持，默认关闭,
            htmlDecode: "style,script,iframe|on*",
            imageUpload: true,
            imageFormats: ["jpg", "jpeg", "gif", "png", "bmp", "webp"],
            imageUploadURL: "/blog/blog-upimage/",
            imageCsrfToken: '{% csrf_token %}',
            path: "{% static 'edittormd/lib/' %}",

            onload: function () {
                initPasteDragImg(this,)
            },
            pluginPath: "{% static 'edittormd/plugins/' %}",
        });

    });

</script>

</body>
</html>
