bglb_blog/urls.py
import notifications.urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bglb_blog import settings
from blog.views import blog_list



urlpatterns = [
    path('admin/admin', admin.site.urls),
  
    path('', blog_list, name='home'),
    path('accounts/', include(('users.urls', 'users'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('oauth/', include(('oauth.urls', 'oauth'), namespace='oauth')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('comment/', include('comments.urls', namespace='comment')),
    path('message/', include('message.urls', namespace='message')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path

from blog import views

urlpatterns = [
    # path函数将url映射到视图
    re_path('blog-list/?key=value/', views.blog_list, name='blog_list'),
    re_path('blog-list/', views.blog_list, name='blog_list'),
    re_path('blog-edit/', views.blog_edit, name='blog_edit'),
    re_path('^blog-edit/?id=value$', views.blog_edit, name='blog_edit'),
    re_path('^(?P<username>\w+)$', views.blog_author, name='blog-author'),
    re_path('^blog-detail/(?P<id>\d+)$', views.blog_detail, name='blog-detail'),
    re_path('blog-publish/', views.blog_publish, name='blog_publish'),
    re_path('blog-delete/', views.blog_delete, name='blog_delete'),
    re_path('blog-upimage/', views.blog_image, name='blog_upimage'),
    re_path('blog-click/', views.blog_click, name='blog_click'),

]

message/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-7-5 14:27
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path
from . import views

app_name = "message"
urlpatterns = [
    # re_path和path的作用都是一样的。只不过re_path是在写url的时候可以用正则表达式，功能更加强大。
    re_path(r'list/', views.show_message, name='message-list'),
    re_path(r'update/', views.update_message, name='message-update'),
]

message/models.py
from django.db import models

# Create your models here.

message/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect, render


@login_required()
def show_message(request):
    """展示消息列表"""

    user = request.user

    msg_unread = user.notifications.unread()

    msg_read = user.notifications.read()

    return render(request, 'message/message.html', locals())


@login_required()
def update_message(request):
    msg_id = request.GET.get('msg_id')
    if request.method == "GET":
        if msg_id:
            article = request.GET.get('article_id')
            comment = request.GET.get('comment_id')
            msg = request.user.notifications.get(id=msg_id)
            msg.mark_as_read()
            return redirect("/blog/blog-detail/{0}#div-comment-{1}".format(int(article), comment), )
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('message:message-list')
    else:
        msg_id = request.POST.get('msg_id')
        if msg_id:
            request.user.notifications.get(id=msg_id).delete()
        else:
            request.user.notifications.all().delete()
        return JsonResponse({"flag": True, "msg": "删除成功！"})

templates/message/message.html
{% extends "base.html" %}
{% load staticfiles %}
{% load user_tags %}
{% block title %}
    消息通知
{% endblock title %}
<style>
    .date:before {
        content: "\f017";
        vertical-align: 4%;
        margin-right: 3px;
        font-size: 15px;
        color: #ccc;
    }
</style>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="list-group col-md-2 text-center">
                <a id="tab1" href="javascript:;" class="tab list-group-item active">未读消息 {% if msg_unread.count > 0 %}
                    <span class="badge badge-danger">{{ msg_unread.count }}</span>
                {% endif %}</a>
                <a id="tab2" href="javascript:;" class="tab list-group-item">系统通知</a>
                <a id="tab3" href="javascript:;" class="tab list-group-item">评论通知</a>
                <a id="tab4" href="javascript:;" class="tab list-group-item">已读消息</a>
            </div>
            <div class="col-md-8">
                <div id="tab-item1" class="tab-item">
                    <div class="row">
                        <h2>未读消息</h2>
                        <a href="{% url 'message:message-update' %}" class="ml-auto">标记所有为已读</a>
                    </div>
                    <hr>
                    <ul class="list-group">
                        {% for notice in msg_unread %}
                            <li class="list-group-item" id="notice_link">
                                <a
                                        href="{% url "message:message-update" %}?article_id={{ notice.target.id }}&msg_id={{ notice.id }}&comment_id={{ notice.action_object.id }}"
                                        target="_blank">
                                <span style="color: #5897fb;">
                                    {{ notice.actor.id| nickname }}
                                </span>
                                    <span style="color: #01a252;"></span> {{ notice.verb }}
                                </a>
                                {{ notice.timestamp|date:"Y/m/d H:i" }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="tab-item2" class="tab-item">
                    <div class="row">
                        <h2>系统通知</h2>
                        <a href="{% url 'message:message-update' %}" class="ml-auto">标记所有为已读</a>
                    </div>
                    <hr>
                    <ul class="list-group">
                        {% for notice in msg_unread %}
                            <li class="list-group-item" id="notice_link">
                                <a
                                        href="{% url "message:message-update" %}?article_id={{ notice.target.id }}&msg_id={{ notice.id }}&comment_id={{ notice.action_object.id }}"
                                        target="_blank">
                                <span style="color: #5897fb;">
                                    {{ notice.actor.id| nickname }}
                                </span>
                                    <span style="color: #01a252;"></span> {{ notice.verb }}
                                </a>
                                {{ notice.timestamp|date:"Y/m/d H:i" }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="tab-item3" class="tab-item">
                    <div class="row">
                        <h2>评论点赞</h2>
                        <a href="{% url 'message:message-update' %}" class="ml-auto">标记所有为已读</a>
                    </div>
                    <hr>
                    <ul class="list-group">
                        {% for notice in msg_unread %}
                            <li class="list-group-item" id="notice_link">
                                <a
                                        href="{% url "message:message-update" %}?article_id={{ notice.target.id }}&msg_id={{ notice.id }}&comment_id={{ notice.action_object.id }}"
                                        target="_blank">
                                <span style="color: #5897fb;">
                                    {{ notice.actor.id| nickname }}
                                </span>
                                    <span style="color: #01a252;"></span> {{ notice.verb }}
                                </a>
                                {{ notice.timestamp|date:"Y/m/d H:i" }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="tab-item4" class="tab-item">
                    <div class="row">
                        <h2>已读消息</h2>
                        <button class="btn btn-link ml-auto del-all">清空所有已读</button>
                    </div>
                    <hr>
                    <ul class="list-group">
                        {% for notice in msg_read %}
                            <li class="list-group-item" id="notice_link">
                                    <span style="color: #5897fb;">
                                        {{ notice.actor.username }}：
                                    </span>
                                {{ notice.verb }}
                                <small><span class="btn btn-link del" id="{{ notice.id }}">删除</span></small>
                                <span class="date">{{ notice.timestamp|date:'yy-m-d H:m' }}</span>
                            </li>
                        {% endfor %}
                        {% csrf_token %}
                    </ul>
                </div>
            </div>
        </div>
        <!-- 未读通知列表 -->
    </div>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/message.js' %}"></script>

{% endblock content %}

