bglb_blog/urls.py
import notifications.urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bglb_blog import settings
from blog.views import blog_list



urlpatterns = [
    path('admin/admin', admin.site.urls),
  
    path('', blog_list, name='home'),
    path('accounts/', include(('users.urls', 'users'), namespace='accounts')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('oauth/', include(('oauth.urls', 'oauth'), namespace='oauth')),
    path('notifications/', include(notifications.urls, namespace='notifications')),
    path('comment/', include('comments.urls', namespace='comment')),
    path('message/', include('message.urls', namespace='message')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-6-10 11:42
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path

from blog import views

urlpatterns = [
    # path函数将url映射到视图
    re_path('blog-list/?key=value/', views.blog_list, name='blog_list'),
    re_path('blog-list/', views.blog_list, name='blog_list'),
    re_path('blog-edit/', views.blog_edit, name='blog_edit'),
    re_path('^blog-edit/?id=value$', views.blog_edit, name='blog_edit'),
    re_path('^(?P<username>\w+)$', views.blog_author, name='blog-author'),
    re_path('^blog-detail/(?P<id>\d+)$', views.blog_detail, name='blog-detail'),
    re_path('blog-publish/', views.blog_publish, name='blog_publish'),
    re_path('blog-delete/', views.blog_delete, name='blog_delete'),
    re_path('blog-upimage/', views.blog_image, name='blog_upimage'),
    re_path('blog-click/', views.blog_click, name='blog_click'),

]

comments/urls.py
# -*- coding:utf-8  -*-
# @Time     : 2020-7-5 14:27
# @Author   : BGLB
# @Software : PyCharm

from django.urls import re_path
from . import views

app_name = "comments"
urlpatterns = [
    re_path(r'post/', views.comment_save, name='post_comment'),
    re_path(r'delete/', views.comment_delete, name='delete_comment'),
]

comments/models.py
from django.contrib.auth.models import User
from django.db import models
from blog.models import BlogPost
from django.utils.timezone import now


# Create your models here.
class Comments(models.Model):
    content = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)
    owner = models.ForeignKey(User, verbose_name='评论人', on_delete=models.CASCADE)
    blog = models.ForeignKey(BlogPost, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', verbose_name="上级评论", blank=True, null=True, on_delete=models.CASCADE)
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)

    class Meta:
        ordering = ['id']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.content

comments/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here
from comments.utils import send_notification
from .models import Comments


@login_required()
def comment_save(request):
    """提交评论"""
    if request.method == "GET":
        return render(request, '404.html')
    owner = request.user
    data = request.POST
    content = data.get('content')
    blog_id = data.get('blog_id')
    parent_id = data.get('parent_comment_id')
    comment = Comments.objects.create(owner=owner, content=content, blog_id=blog_id)
    if parent_id is not '0':
        parent_comment = Comments.objects.get(pk=parent_id)
        comment.parent_comment = parent_comment
    comment.save()
    flag = True
    msg = "评论成功"
    send_notification(comment)
    return JsonResponse({'flag': flag, 'msg': msg})


@login_required()
def comment_delete(request):
    """删除评论"""
    if request.method == "GET":
        return render(request, '404.html')
    try:
        comment = Comments.objects.get(id=request.POST.get('id'))
        comment.delete()
        flag = True
        msg = "删除成功"
    except Exception as e:
        flag = False
        msg = "数据错误"
    return JsonResponse({'flag': flag, 'msg': msg})

templates/comments/comment_item_tree.html
<style>
    .author-avatar {
        color: #D4D4D4;
        width: 35px;
        height: 35px;
        border-radius: 50%;
        display: inline-block;
        margin-top: 0;
        background-color: #eee;
        vertical-align: top;
        float: left;
        margin-right: 10px;
    }
</style>
{% load user_tags %}
{% load blog_tools %}
{% load comments_tags %}
<li class="comment even thread-even depth-{{ depth }} parent" id="comment-{{ comment_item.pk }}"
    style="margin-left: {% widthratio depth 1 3 %}rem">
    <div id="div-comment-{{ comment_item.pk }}" class="comment-body">
        <div class="comment-author vcard">
            <img alt=""
                 src="{{ comment_item.owner.id|avatar_url }}"
                 srcset="{{ comment_item.owner.id|avatar_url }}"
                 class="author-avatar">
            <cite class="fn">
                <a rel="nofollow" style="line-height: 35px"
                   href="{% url 'blog:blog-author' comment_item.owner.username %}"
                   rel="external nofollow"
                   class="url">{{ comment_item.owner.id|nickname }}
                </a>：<span>{{ comment_item.content }}</span>
            </cite>
        </div>
        <div class="comment-meta commentmetadata">
            {{ comment_item.created_time|blog_pub_time }}
        </div>
        <div class="reply">
            <a rel="nofollow" class="comment-reply-link"
               href="javascript:void(0)"
               onclick="do_reply({{ comment_item.pk }},'回复 {{ comment_item.owner.id|nickname }}')"
               aria-label="回复 {{ comment_item.owner.id|nickname }}">
                回复
            </a>
            {% if request.user == comment_item.blog.author or request.user == comment_item.owner %}
                <a rel="nofollow" class="comment-reply-link del"
                   href="javascript:void(0)"
                   onclick="del({{ comment_item.id }})"
                >
                    删除
                </a>
            {% endif %}
        </div>
    </div>
    <hr>
</li>
{% query blog_comments parent_comment=comment_item as cc_comments %}
{% for cc in cc_comments %}
    {% with comment_item=cc template_name="comments/comment_item_tree.html" %}
        {% with depth=depth|add:1 %}
            {% include template_name %}
        {% endwith %}
    {% endwith %}
{% endfor %}
{% csrf_token %}

<script>

    function do_reply(parentid, text) {
        $(".parent_comment_id").val(parentid);
        $("#commentform").appendTo($("#div-comment-" + parentid));
        $('.content').addClass('open');
        $('.content').attr('placeholder', text);
        $("#reply-title").hide();
        $("#cancel_comment").show();
    };

    function del(id) {
        let token = $('[name="csrfmiddlewaretoken"]').attr("value");
        $.ajax({
            url: '/comment/delete/',
            type: 'post',
            data: {
                "csrfmiddlewaretoken": token,
                'id': id,
            },
            success: function (data) {
                bs4pop.notice(data.msg, {type: data.flag ? 'success' : 'danger', position: 'topcenter'});
                if (data.flag) {
                    setTimeout(function () {
                        window.location.reload()
                    }, 500)
                }
            }
        });
    }
</script>

templates/comments/comment_list.html
<section id="comments" class="themeform">
    {% load user_tags %}
    {% load comments_tags %}
    <hr>
    {% if blog_comments %}
        <div id="commentlist-container" class="comment-tab" style="display: block;">
            <ol class="commentlist">
                {% query blog_comments parent_comment=None as parent_comments %}
                {% for comment_item in parent_comments %}
                    {% with 0 as depth %}
                        {% include "comments/comment_item_tree.html" %}
                    {% endwith %}
                {% endfor %}
            </ol>
        </div>
        {%  else %}
        <p>暂时没有评论</p>
    {% endif %}


</section>

templates/comments/post_comment.html
{% load user_tags %}
<div id="comments" class="comments-area">

    <div id="respond" class="comment-respond">
        <form action="{% url 'comment:post_comment' %}" method="post" id="commentform"
              class="comment-form">{% csrf_token %}
            <textarea type="text" placeholder="博主需要您的鼓励，才能有动力创作" name="content"
                      class="content"></textarea>
            <input type="text" style="display: none;" name="parent_comment_id" class="parent_comment_id">
            <div class="form-submit text-center">
                <input name="submit" type="button" id="post_submit" class="btn btn-success col-xm-12 col-md-1"
                       value="提交" readonly>
                <small class="cancel-comment" id="cancel_comment" style="display: none">
                    <a href="javascript:;" class="btn btn-dark cancel" onclick="cancel_reply()">取消</a>
                </small>
            </div>
        </form>

    </div>

</div>

